"""Deterministic local Compose configuration generation."""

from __future__ import annotations

import os
from pathlib import Path
import tempfile

from .discover import HostFacts
from .envfile import update_env
from .secrets import ensure_service_credentials


DIRECT_PORTS = (("jellyseerr", 5055), ("radarr", 7878), ("sonarr", 8989))


def _quicksync_usable(facts: HostFacts) -> bool:
    return facts.graphics.quicksync_usable


def build_override(facts: HostFacts, direct_setup_ports: bool) -> str:
    """Render only bounded, known host adaptations in deterministic YAML."""

    services: list[tuple[str, list[str]]] = []
    if _quicksync_usable(facts):
        services.append(("jellyfin", ["    devices:", "      - /dev/dri:/dev/dri"]))
    ports_enabled = direct_setup_ports or facts.lan_dns_status != "resolved"
    if ports_enabled:
        for service, port in DIRECT_PORTS:
            services.append((service, ["    ports:", f'      - "{port}:{port}"']))
    if not services:
        return "services: {}\n"
    lines = ["# Generated by scripts/homeflix; local host adaptations only.", "services:"]
    for service, body in services:
        lines.append(f"  {service}:")
        lines.extend(body)
    return "\n".join(lines) + "\n"


def _atomic_write(path: Path, contents: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    descriptor: int | None = None
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
        )
        os.fchmod(descriptor, mode)
        temporary = os.fdopen(descriptor, "w", encoding="utf-8", newline="")
        descriptor = None  # fdopen owns the descriptor after a successful call.
        with temporary:
            temporary.write(contents)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_name, path)
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if temporary_name is not None:
            Path(temporary_name).unlink(missing_ok=True)


def _validated_path(name: str, value: str, facts: HostFacts) -> str:
    path = Path(value).expanduser()
    if not path.is_absolute():
        raise ValueError(f"{name} must be an absolute path")
    if not path.exists():
        raise ValueError(f"{name} does not exist; mount storage before configuring Homeflix")
    if not path.is_dir():
        raise ValueError(f"{name} must be an existing directory")
    if not os.access(path, os.W_OK | os.X_OK):
        raise ValueError(f"{name} must be writable by the deployment user")
    if facts.mounts_status != "ok":
        raise ValueError(f"{name} cannot be verified because mount discovery is unavailable")
    resolved = path.resolve()
    matching_mounts: list[Path] = []
    for mount in facts.mounts:
        target = Path(mount.target).resolve()
        try:
            resolved.relative_to(target)
            matching_mounts.append(target)
        except ValueError:
            continue
    if not matching_mounts:
        raise ValueError(f"{name} is not under a discovered mounted filesystem")
    containing_mount = max(matching_mounts, key=lambda item: len(item.parts))
    if name == "DATA_ROOT" and containing_mount == Path("/"):
        raise ValueError("DATA_ROOT is only on the host root filesystem; mount storage before configuring Homeflix")
    return str(resolved)


def configure(
    repository_root: str | os.PathLike[str],
    facts: HostFacts,
    *,
    data_root: str,
    config_root: str,
    cache_root: str,
    quality_profile: str = "HD-1080p",
    direct_setup_ports: bool = False,
) -> dict[str, object]:
    """Generate mode-0600 configuration and an ignored deterministic override."""

    if not facts.supported:
        raise ValueError("configuration is supported only on discovered Debian and Ubuntu hosts")
    if facts.uid is None or facts.gid is None or not facts.timezone:
        raise ValueError("UID, GID, and timezone must be discovered before configuration")
    roots = {
        "DATA_ROOT": _validated_path("DATA_ROOT", data_root, facts),
        "CONFIG_ROOT": _validated_path("CONFIG_ROOT", config_root, facts),
        "CACHE_ROOT": _validated_path("CACHE_ROOT", cache_root, facts),
    }
    if "\n" in quality_profile or "\r" in quality_profile or "\0" in quality_profile:
        raise ValueError("quality profile contains forbidden control characters")
    root = Path(repository_root)
    env_path = root / ".env"
    if not env_path.exists():
        example_path = root / ".env.example"
        _atomic_write(env_path, example_path.read_text(encoding="utf-8"), 0o600)
    updates = {
        **roots,
        "PUID": str(facts.uid),
        "PGID": str(facts.gid),
        "TZ": facts.timezone,
        "COMPOSE_PROJECT_NAME": "homeflix",
        "QUALITY_PROFILE": quality_profile,
    }
    environment_result = update_env(env_path, updates)
    credentials_result = ensure_service_credentials(env_path)
    override_path = root / "docker-compose.override.yml"
    override = build_override(facts, direct_setup_ports)
    if not override_path.exists() or override_path.read_text(encoding="utf-8") != override:
        _atomic_write(override_path, override, 0o644)
        override_status = "updated"
    else:
        override_status = "unchanged"
    return {
        "environment": environment_result,
        "credentials": credentials_result["credentials"],
        "override": {"status": override_status, "adaptations": {
            "quicksync": _quicksync_usable(facts),
            "direct_setup_ports": direct_setup_ports or facts.lan_dns_status != "resolved",
        }},
    }
