"""Deterministic local Compose configuration and execution helpers."""

from __future__ import annotations

import ipaddress
import json
import os
from pathlib import Path
import re
import subprocess
import tempfile
from typing import Mapping, Protocol, Sequence

from .discover import ALLOWED_LAN_NETWORKS, HostFacts
from .envfile import EnvDocument, update_env
from .secrets import ensure_service_credentials


DIRECT_PORTS = (("jellyseerr", 5055), ("radarr", 7878), ("sonarr", 8989))
# VPN providers terminate the tunnel on a gateway inside private address space. Allowing a
# subnet that contains one makes Gluetun route the provider's own gateway to the LAN, which
# breaks NAT-PMP port forwarding while the tunnel still reports healthy.
VPN_GATEWAYS = (ipaddress.ip_address("10.2.0.1"),)
# Candidates for the Docker proxy network, tried in order. Pinning it keeps the firewall
# allowlist stable; an unpinned bridge can be reallocated on any recreate.
PROXY_SUBNET_CANDIDATES = ("172.30.0.0/24", "172.31.0.0/24", "192.168.246.0/24")
ALLOWED_PROXY_NETWORKS = tuple(
    ipaddress.ip_network(cidr)
    for cidr in ("10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16")
)
CORE_SERVICES = ("traefik", "jellyfin", "jellyseerr", "radarr", "sonarr")
# Optional Compose helpers. Not started by core or acquisition; may already be running.
SUPPORT_SERVICES = ("deunhealth", "glances", "watchtower")
GLUETUN_SERVICES = ("gluetun",)
ACQUISITION_SERVICES = ("gluetun", "qbittorrent", "nzbget", "prowlarr")
ACQUISITION_CLIENT_SERVICES = ("qbittorrent", "nzbget")
_COMPOSE_STATES = {"created", "dead", "exited", "paused", "removing", "restarting", "running"}
_COMPOSE_HEALTH = {"", "healthy", "starting", "unhealthy"}
_COMPOSE_SERVICE_NAME = re.compile(r"[a-z0-9][a-z0-9_.-]*\Z", re.ASCII)
_COMPOSE_PROJECT_NAME = re.compile(r"[a-z0-9][a-z0-9_-]*\Z", re.ASCII)


class Runner(Protocol):
    def run(
        self,
        argv: Sequence[str],
        *,
        input_text: str | None = None,
        check: bool = False,
        timeout: float | None = None,
    ) -> subprocess.CompletedProcess[str]: ...


def _quicksync_usable(facts: HostFacts) -> bool:
    return facts.graphics.quicksync_usable


def build_override(facts: HostFacts, direct_setup_ports: bool) -> str:
    """Render only bounded, known host adaptations in deterministic YAML."""

    services: list[tuple[str, list[str]]] = []
    if _quicksync_usable(facts):
        services.append(("jellyfin", ["    devices:", "      - /dev/dri:/dev/dri"]))
    ports_enabled = direct_setup_ports or facts.lan_dns_status != "resolved"
    if ports_enabled:
        for service, port in DIRECT_PORTS:
            services.append((service, ["    ports:", f'      - "{port}:{port}"']))
    if not services:
        return "services: {}\n"
    lines = ["# Generated by scripts/homeflix; local host adaptations only.", "services:"]
    for service, body in services:
        lines.append(f"  {service}:")
        lines.extend(body)
    return "\n".join(lines) + "\n"


def _atomic_write(path: Path, contents: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    descriptor: int | None = None
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
        )
        os.fchmod(descriptor, mode)
        temporary = os.fdopen(descriptor, "w", encoding="utf-8", newline="")
        descriptor = None
        with temporary:
            temporary.write(contents)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_name, path)
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if temporary_name is not None:
            Path(temporary_name).unlink(missing_ok=True)


def _validated_lan_subnet(facts: HostFacts) -> ipaddress.IPv4Network | ipaddress.IPv6Network:
    network = facts.lan_network
    if network.status != "ok" or not network.cidr:
        raise ValueError(
            "LAN_SUBNET cannot be determined because LAN discovery is unavailable "
            f"({network.reason or network.status}); reconnect the LAN and retry discovery, "
            "or use the manual quickstart"
        )
    subnet = ipaddress.ip_network(network.cidr)
    if subnet.version != 4 or not any(
        subnet.subnet_of(allowed) for allowed in ALLOWED_LAN_NETWORKS
    ):
        raise ValueError(
            f"discovered LAN subnet {subnet} is outside allowed local-use address space; "
            "public VPN bypasses are refused"
        )
    for gateway in VPN_GATEWAYS:
        if gateway in subnet:
            raise ValueError(
                f"discovered LAN subnet {subnet} contains VPN gateway {gateway}; "
                "port forwarding cannot work on this network"
            )
    return subnet


def _selected_proxy_subnet(
    lan_subnet: ipaddress.IPv4Network | ipaddress.IPv6Network,
    routed_cidrs: Sequence[str],
    existing_cidr: str | None,
) -> str:
    routed_networks = tuple(ipaddress.ip_network(cidr) for cidr in routed_cidrs)

    def safe(subnet: ipaddress.IPv4Network | ipaddress.IPv6Network) -> bool:
        return (
            subnet.version == 4
            and any(subnet.subnet_of(allowed) for allowed in ALLOWED_PROXY_NETWORKS)
            and not subnet.overlaps(lan_subnet)
            and not any(gateway in subnet for gateway in VPN_GATEWAYS)
        )

    if existing_cidr is not None:
        existing = ipaddress.ip_network(existing_cidr)
        if not safe(existing):
            raise ValueError(
                f"existing Homeflix proxy subnet {existing} conflicts with the LAN or VPN gateway"
            )
        if any(
            routed.version == existing.version
            and routed.overlaps(existing)
            and routed != existing
            for routed in routed_networks
        ):
            raise ValueError(
                f"existing Homeflix proxy subnet {existing} overlaps another host route"
            )
        return str(existing)

    for candidate in PROXY_SUBNET_CANDIDATES:
        subnet = ipaddress.ip_network(candidate)
        if not safe(subnet):
            continue
        if any(
            subnet.version == routed.version and subnet.overlaps(routed)
            for routed in routed_networks
        ):
            continue
        return candidate
    raise ValueError(
        f"no supported proxy subnet candidate is free alongside LAN subnet {lan_subnet} "
        "and the host's existing IPv4 routes; remove the conflicting route or use the "
        "manual quickstart with a verified PROXY_SUBNET"
    )


def _validated_path(name: str, value: str, facts: HostFacts) -> str:
    path = Path(value).expanduser()
    if not path.is_absolute():
        raise ValueError(f"{name} must be an absolute path")
    if not path.exists():
        raise ValueError(f"{name} does not exist; mount storage before configuring Homeflix")
    if not path.is_dir():
        raise ValueError(f"{name} must be an existing directory")
    if not os.access(path, os.W_OK | os.X_OK):
        raise ValueError(f"{name} must be writable by the deployment user")
    if facts.mounts_status != "ok":
        raise ValueError(f"{name} cannot be verified because mount discovery is unavailable")
    resolved = path.resolve()
    matching_mounts: list[Path] = []
    for mount in facts.mounts:
        target = Path(mount.target).resolve()
        try:
            resolved.relative_to(target)
            matching_mounts.append(target)
        except ValueError:
            continue
    if not matching_mounts:
        raise ValueError(f"{name} is not under a discovered mounted filesystem")
    containing_mount = max(matching_mounts, key=lambda item: len(item.parts))
    if name == "DATA_ROOT" and containing_mount == Path("/"):
        raise ValueError("DATA_ROOT is only on the host root filesystem; mount storage before configuring Homeflix")
    return str(resolved)


def configure(
    repository_root: str | os.PathLike[str],
    facts: HostFacts,
    *,
    data_root: str,
    config_root: str,
    cache_root: str,
    quality_profile: str = "HD-1080p",
    direct_setup_ports: bool = False,
) -> dict[str, object]:
    """Generate mode-0600 configuration and an ignored deterministic override."""

    if not facts.supported:
        raise ValueError("configuration is supported only on discovered Debian and Ubuntu hosts")
    if facts.uid is None or facts.gid is None or not facts.timezone:
        raise ValueError("UID, GID, and timezone must be discovered before configuration")
    roots = {
        "DATA_ROOT": _validated_path("DATA_ROOT", data_root, facts),
        "CONFIG_ROOT": _validated_path("CONFIG_ROOT", config_root, facts),
        "CACHE_ROOT": _validated_path("CACHE_ROOT", cache_root, facts),
    }
    lan_subnet = _validated_lan_subnet(facts)
    if facts.proxy_network.status not in {"absent", "ok"}:
        raise ValueError(
            "PROXY_SUBNET cannot be verified because Homeflix proxy network ownership "
            f"could not be established ({facts.proxy_network.reason or facts.proxy_network.status})"
        )
    if facts.proxy_network.status == "ok" and not facts.proxy_network.cidr:
        raise ValueError("PROXY_SUBNET cannot be verified from empty Homeflix network IPAM")
    existing_proxy_cidr = (
        facts.proxy_network.cidr if facts.proxy_network.status == "ok" else None
    )
    proxy_subnet = _selected_proxy_subnet(
        lan_subnet,
        facts.lan_network.routed_cidrs,
        existing_proxy_cidr,
    )
    if "\n" in quality_profile or "\r" in quality_profile or "\0" in quality_profile:
        raise ValueError("quality profile contains forbidden control characters")
    root = Path(repository_root)
    env_path = root / ".env"
    if not env_path.exists():
        example_path = root / ".env.example"
        _atomic_write(env_path, example_path.read_text(encoding="utf-8"), 0o600)
    updates = {
        **roots,
        "PUID": str(facts.uid),
        "PGID": str(facts.gid),
        "TZ": facts.timezone,
        "COMPOSE_PROJECT_NAME": "homeflix",
        "QUALITY_PROFILE": quality_profile,
        "LAN_SUBNET": str(lan_subnet),
        "PROXY_SUBNET": proxy_subnet,
        "PROXY_NETWORK_SUBNET": proxy_subnet,
    }
    environment_result = update_env(env_path, updates)
    credentials_result = ensure_service_credentials(env_path)
    override_path = root / "docker-compose.override.yml"
    override = build_override(facts, direct_setup_ports)
    if not override_path.exists() or override_path.read_text(encoding="utf-8") != override:
        _atomic_write(override_path, override, 0o644)
        override_status = "updated"
    else:
        override_status = "unchanged"
    return {
        "environment": environment_result,
        "credentials": credentials_result["credentials"],
        "override": {"status": override_status, "adaptations": {
            "quicksync": _quicksync_usable(facts),
            "direct_setup_ports": direct_setup_ports or facts.lan_dns_status != "resolved",
        }},
    }


def _validated_project_name(value: str | None) -> str:
    normalized = value.strip() if isinstance(value, str) else ""
    if _COMPOSE_PROJECT_NAME.fullmatch(normalized) is None:
        raise ValueError("COMPOSE_PROJECT_NAME must use lowercase ASCII Compose project-name syntax")
    return normalized


_ARR_DATA_SERVICES = ("radarr", "sonarr", "lidarr")


def _service_blocks(source: str) -> dict[str, str]:
    """Split top-level Compose service mappings from the project file."""
    blocks: dict[str, list[str]] = {}
    current: str | None = None
    in_services = False
    for line in source.splitlines():
        if line.startswith("services:"):
            in_services = True
            current = None
            continue
        if not in_services:
            continue
        if line and not line.startswith(" ") and not line.startswith("\t"):
            break
        if re.fullmatch(r"  [A-Za-z0-9][A-Za-z0-9_.-]*:\s*", line):
            current = line.strip()[:-1]
            blocks[current] = [line]
            continue
        if current is not None:
            blocks[current].append(line)
    return {name: "\n".join(body) for name, body in blocks.items()}


def _restore_omitted_create_host_path(rendered: dict[str, object], source: str) -> dict[str, object]:
    """Older Compose drops create_host_path: false from JSON; restore from source."""
    services = rendered.get("services")
    if not isinstance(services, dict):
        return rendered
    declared = {
        name: "create_host_path: false" in block
        for name, block in _service_blocks(source).items()
    }
    for name in _ARR_DATA_SERVICES:
        service = services.get(name)
        if not isinstance(service, dict) or not declared.get(name):
            continue
        volumes = service.get("volumes")
        if not isinstance(volumes, list):
            continue
        for volume in volumes:
            if not isinstance(volume, dict) or volume.get("target") != "/data":
                continue
            bind = volume.get("bind")
            if bind is None:
                volume["bind"] = {"create_host_path": False}
            elif isinstance(bind, dict) and "create_host_path" not in bind:
                bind["create_host_path"] = False
    return rendered


def render_compose_config(repository_root: str | os.PathLike[str]) -> dict[str, object]:
    """Render Compose once to a mapping. The stack-contract module never calls this."""

    root = Path(repository_root).resolve()
    env_file = root / ".env" if (root / ".env").exists() else root / ".env.example"
    result = subprocess.run(
        (
            "docker",
            "compose",
            "--project-directory",
            str(root),
            "--env-file",
            str(env_file),
            "config",
            "--format",
            "json",
        ),
        text=True,
        capture_output=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError("rendered Compose configuration could not be produced")
    try:
        rendered = json.loads(result.stdout)
    except json.JSONDecodeError as error:
        raise RuntimeError("rendered Compose configuration was not valid JSON") from error
    if not isinstance(rendered, dict):
        raise RuntimeError("rendered Compose configuration was not an object")
    source = (root / "docker-compose.yml").read_text(encoding="utf-8")
    return _restore_omitted_create_host_path(rendered, source)


def compose_command(
    repository_root: str | os.PathLike[str], *, project_name: str | None = None
) -> tuple[str, ...]:
    """Return the explicit, cwd-independent Compose command prefix."""

    root = Path(repository_root).resolve()
    return (
        "docker", "compose", "--project-directory", str(root),
        "--env-file", str(root / ".env"), "--project-name",
        _validated_project_name(
            project_name if project_name is not None else EnvDocument.load(root / ".env").get("COMPOSE_PROJECT_NAME")
        ),
    )


def _compose_up_allowlist(
    repository_root: str | os.PathLike[str],
    services: Sequence[str],
    runner: Runner,
    allowlist: Sequence[str],
    *,
    label: str,
    project_name: str | None = None,
    timeout: float = 300,
) -> subprocess.CompletedProcess[str]:
    selected = tuple(services)
    permitted = tuple(allowlist)
    if not selected or any(service not in permitted for service in selected):
        raise ValueError(f"Compose {label} deployment services must come from the {label} allowlist")
    argv = (
        *compose_command(repository_root, project_name=project_name),
        "up", "--detach", "--no-deps", *selected,
    )
    if timeout <= 0:
        raise TimeoutError("Compose startup deadline exhausted")
    return runner.run(argv, check=False, timeout=min(300, timeout))


def compose_up(
    repository_root: str | os.PathLike[str],
    services: Sequence[str],
    runner: Runner,
    *,
    project_name: str | None = None,
    timeout: float = 300,
) -> subprocess.CompletedProcess[str]:
    """Start exactly the named core services; callers must perform preflight first."""

    return _compose_up_allowlist(
        repository_root,
        services,
        runner,
        CORE_SERVICES,
        label="core",
        project_name=project_name,
        timeout=timeout,
    )


def compose_up_gluetun(
    repository_root: str | os.PathLike[str],
    services: Sequence[str],
    runner: Runner,
    *,
    project_name: str | None = None,
    timeout: float = 300,
) -> subprocess.CompletedProcess[str]:
    """Start exactly Gluetun. Gated download/indexer services stay off this path."""

    return _compose_up_allowlist(
        repository_root,
        services,
        runner,
        GLUETUN_SERVICES,
        label="gluetun",
        project_name=project_name,
        timeout=timeout,
    )


def compose_up_acquisition(
    repository_root: str | os.PathLike[str],
    services: Sequence[str],
    runner: Runner,
    *,
    project_name: str | None = None,
    timeout: float = 300,
) -> subprocess.CompletedProcess[str]:
    """Start selected acquisition services from the widened allowlist."""

    return _compose_up_allowlist(
        repository_root,
        services,
        runner,
        ACQUISITION_SERVICES,
        label="acquisition",
        project_name=project_name,
        timeout=timeout,
    )


def compose_stop_acquisition(
    repository_root: str | os.PathLike[str],
    services: Sequence[str],
    runner: Runner,
    *,
    project_name: str | None = None,
    timeout: float = 60,
) -> subprocess.CompletedProcess[str]:
    """Stop unselected download clients. Never deletes volumes or host data."""

    selected = tuple(services)
    if not selected or any(service not in ACQUISITION_CLIENT_SERVICES for service in selected):
        raise ValueError("Compose acquisition stop services must come from the acquisition client allowlist")
    argv = (*compose_command(repository_root, project_name=project_name), "stop", *selected)
    if timeout <= 0:
        raise TimeoutError("Compose stop deadline exhausted")
    return runner.run(argv, check=False, timeout=min(60, timeout))


def _json_records(text: str) -> list[object]:
    stripped = text.strip()
    if not stripped:
        return []
    try:
        value = json.loads(stripped)
    except json.JSONDecodeError:
        records: list[object] = []
        for line in stripped.splitlines():
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as error:
                raise ValueError("Compose service state was malformed") from error
        return records
    return value if isinstance(value, list) else [value]


def compose_inventory(
    repository_root: str | os.PathLike[str],
    runner: Runner,
    *,
    project_name: str | None = None,
    timeout: float = 30,
) -> list[dict[str, str]]:
    """Return validated live Compose records including their project identity."""
    expected = _validated_project_name(project_name)
    result = runner.run(
        (*compose_command(repository_root, project_name=expected), "ps", "--all", "--format", "json"),
        check=False, timeout=timeout,
    )
    if result.returncode:
        raise RuntimeError("Compose service inventory is unavailable")
    inventory: list[dict[str, str]] = []
    for record in _json_records(result.stdout):
        if not isinstance(record, Mapping):
            raise ValueError("Compose service inventory was malformed")
        values = {
            "service": record.get("Service", record.get("service")),
            "state": record.get("State", record.get("state")),
            "health": record.get("Health", record.get("health", "")),
            "project": record.get("Project", record.get("project")),
        }
        if not all(isinstance(value, str) for value in values.values()):
            raise ValueError("Compose service inventory was malformed")
        service = values["service"]
        project = values["project"]
        state = values["state"].strip().casefold()
        health = values["health"].strip().casefold()
        if (
            service != service.strip() or project != project.strip()
            or not service.isascii() or not project.isascii()
            or _COMPOSE_SERVICE_NAME.fullmatch(service) is None
            or state not in _COMPOSE_STATES
            or health not in _COMPOSE_HEALTH
            or _COMPOSE_PROJECT_NAME.fullmatch(project) is None
        ):
            raise ValueError("Compose service inventory was malformed")
        inventory.append({"service": service, "state": state, "health": health, "project": project})
    if len({item["service"] for item in inventory}) != len(inventory):
        raise ValueError("Compose service inventory was malformed")
    return inventory


def compose_ps(
    repository_root: str | os.PathLike[str],
    runner: Runner,
    *,
    project_name: str | None = None,
    timeout: float = 30,
) -> dict[str, dict[str, str]]:
    """Read Compose v2 service state, accepting array and JSON-lines output."""

    result = runner.run(
        (*compose_command(repository_root, project_name=project_name), "ps", "--format", "json"),
        check=False,
        timeout=timeout,
    )
    if result.returncode:
        raise RuntimeError("Compose service state is unavailable")
    records = _json_records(result.stdout)
    states: dict[str, dict[str, str]] = {}
    for record in records:
        if not isinstance(record, Mapping):
            raise ValueError("Compose service state was malformed")
        service_value = record.get("Service", record.get("service"))
        state_value = record.get("State", record.get("state"))
        health_value = record.get("Health", record.get("health", ""))
        if not all(isinstance(value, str) for value in (service_value, state_value, health_value)):
            raise ValueError("Compose service state was malformed")
        raw_service = service_value.strip()
        if not raw_service.isascii():
            raise ValueError("Compose service state was malformed")
        service = raw_service.casefold()
        state = state_value.strip().casefold()
        health = health_value.strip().casefold()
        if not service or not state or (health_value and not health):
            raise ValueError("Compose service state was malformed")
        if _COMPOSE_SERVICE_NAME.fullmatch(service) is None:
            raise ValueError("Compose service state was malformed")
        if state not in _COMPOSE_STATES or health not in _COMPOSE_HEALTH or service in states:
            raise ValueError("Compose service state was malformed")
        states[service] = {"state": state, "health": health}
    return states
