"""Deterministic local Compose configuration and execution helpers."""

from __future__ import annotations

import json
import os
from pathlib import Path
import re
import subprocess
import tempfile
from typing import Mapping, Protocol, Sequence

from .discover import HostFacts
from .envfile import EnvDocument, update_env
from .secrets import ensure_service_credentials


DIRECT_PORTS = (("jellyseerr", 5055), ("radarr", 7878), ("sonarr", 8989))
CORE_SERVICES = ("traefik", "jellyfin", "jellyseerr", "radarr", "sonarr")
_COMPOSE_STATES = {"created", "dead", "exited", "paused", "removing", "restarting", "running"}
_COMPOSE_HEALTH = {"", "healthy", "starting", "unhealthy"}
_COMPOSE_SERVICE_NAME = re.compile(r"[a-z0-9][a-z0-9_.-]*\Z", re.ASCII)
_COMPOSE_PROJECT_NAME = re.compile(r"[a-z0-9][a-z0-9_-]*\Z", re.ASCII)


class Runner(Protocol):
    def run(
        self,
        argv: Sequence[str],
        *,
        input_text: str | None = None,
        check: bool = False,
        timeout: float | None = None,
    ) -> subprocess.CompletedProcess[str]: ...


def _quicksync_usable(facts: HostFacts) -> bool:
    return facts.graphics.quicksync_usable


def build_override(facts: HostFacts, direct_setup_ports: bool) -> str:
    """Render only bounded, known host adaptations in deterministic YAML."""

    services: list[tuple[str, list[str]]] = []
    if _quicksync_usable(facts):
        services.append(("jellyfin", ["    devices:", "      - /dev/dri:/dev/dri"]))
    ports_enabled = direct_setup_ports or facts.lan_dns_status != "resolved"
    if ports_enabled:
        for service, port in DIRECT_PORTS:
            services.append((service, ["    ports:", f'      - "{port}:{port}"']))
    if not services:
        return "services: {}\n"
    lines = ["# Generated by scripts/homeflix; local host adaptations only.", "services:"]
    for service, body in services:
        lines.append(f"  {service}:")
        lines.extend(body)
    return "\n".join(lines) + "\n"


def _atomic_write(path: Path, contents: str, mode: int) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    descriptor: int | None = None
    try:
        descriptor, temporary_name = tempfile.mkstemp(
            dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
        )
        os.fchmod(descriptor, mode)
        temporary = os.fdopen(descriptor, "w", encoding="utf-8", newline="")
        descriptor = None
        with temporary:
            temporary.write(contents)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.replace(temporary_name, path)
    finally:
        if descriptor is not None:
            os.close(descriptor)
        if temporary_name is not None:
            Path(temporary_name).unlink(missing_ok=True)


def _validated_path(name: str, value: str, facts: HostFacts) -> str:
    path = Path(value).expanduser()
    if not path.is_absolute():
        raise ValueError(f"{name} must be an absolute path")
    if not path.exists():
        raise ValueError(f"{name} does not exist; mount storage before configuring Homeflix")
    if not path.is_dir():
        raise ValueError(f"{name} must be an existing directory")
    if not os.access(path, os.W_OK | os.X_OK):
        raise ValueError(f"{name} must be writable by the deployment user")
    if facts.mounts_status != "ok":
        raise ValueError(f"{name} cannot be verified because mount discovery is unavailable")
    resolved = path.resolve()
    matching_mounts: list[Path] = []
    for mount in facts.mounts:
        target = Path(mount.target).resolve()
        try:
            resolved.relative_to(target)
            matching_mounts.append(target)
        except ValueError:
            continue
    if not matching_mounts:
        raise ValueError(f"{name} is not under a discovered mounted filesystem")
    containing_mount = max(matching_mounts, key=lambda item: len(item.parts))
    if name == "DATA_ROOT" and containing_mount == Path("/"):
        raise ValueError("DATA_ROOT is only on the host root filesystem; mount storage before configuring Homeflix")
    return str(resolved)


def configure(
    repository_root: str | os.PathLike[str],
    facts: HostFacts,
    *,
    data_root: str,
    config_root: str,
    cache_root: str,
    quality_profile: str = "HD-1080p",
    direct_setup_ports: bool = False,
) -> dict[str, object]:
    """Generate mode-0600 configuration and an ignored deterministic override."""

    if not facts.supported:
        raise ValueError("configuration is supported only on discovered Debian and Ubuntu hosts")
    if facts.uid is None or facts.gid is None or not facts.timezone:
        raise ValueError("UID, GID, and timezone must be discovered before configuration")
    roots = {
        "DATA_ROOT": _validated_path("DATA_ROOT", data_root, facts),
        "CONFIG_ROOT": _validated_path("CONFIG_ROOT", config_root, facts),
        "CACHE_ROOT": _validated_path("CACHE_ROOT", cache_root, facts),
    }
    if "\n" in quality_profile or "\r" in quality_profile or "\0" in quality_profile:
        raise ValueError("quality profile contains forbidden control characters")
    root = Path(repository_root)
    env_path = root / ".env"
    if not env_path.exists():
        example_path = root / ".env.example"
        _atomic_write(env_path, example_path.read_text(encoding="utf-8"), 0o600)
    updates = {
        **roots,
        "PUID": str(facts.uid),
        "PGID": str(facts.gid),
        "TZ": facts.timezone,
        "COMPOSE_PROJECT_NAME": "homeflix",
        "QUALITY_PROFILE": quality_profile,
    }
    environment_result = update_env(env_path, updates)
    credentials_result = ensure_service_credentials(env_path)
    override_path = root / "docker-compose.override.yml"
    override = build_override(facts, direct_setup_ports)
    if not override_path.exists() or override_path.read_text(encoding="utf-8") != override:
        _atomic_write(override_path, override, 0o644)
        override_status = "updated"
    else:
        override_status = "unchanged"
    return {
        "environment": environment_result,
        "credentials": credentials_result["credentials"],
        "override": {"status": override_status, "adaptations": {
            "quicksync": _quicksync_usable(facts),
            "direct_setup_ports": direct_setup_ports or facts.lan_dns_status != "resolved",
        }},
    }


def _validated_project_name(value: str | None) -> str:
    normalized = value.strip() if isinstance(value, str) else ""
    if _COMPOSE_PROJECT_NAME.fullmatch(normalized) is None:
        raise ValueError("COMPOSE_PROJECT_NAME must use lowercase ASCII Compose project-name syntax")
    return normalized


def compose_command(
    repository_root: str | os.PathLike[str], *, project_name: str | None = None
) -> tuple[str, ...]:
    """Return the explicit, cwd-independent Compose command prefix."""

    root = Path(repository_root).resolve()
    return (
        "docker", "compose", "--project-directory", str(root),
        "--env-file", str(root / ".env"), "--project-name",
        _validated_project_name(
            project_name if project_name is not None else EnvDocument.load(root / ".env").get("COMPOSE_PROJECT_NAME")
        ),
    )


def compose_up(
    repository_root: str | os.PathLike[str],
    services: Sequence[str],
    runner: Runner,
    *,
    project_name: str | None = None,
    timeout: float = 300,
) -> subprocess.CompletedProcess[str]:
    """Start exactly the named services; callers must perform preflight first."""

    selected = tuple(services)
    if not selected or any(service not in CORE_SERVICES for service in selected):
        raise ValueError("Compose core deployment services must come from CORE_SERVICES")
    argv = (
        *compose_command(repository_root, project_name=project_name),
        "up", "--detach", "--no-deps", *selected,
    )
    if timeout <= 0:
        raise TimeoutError("Compose startup deadline exhausted")
    return runner.run(argv, check=False, timeout=min(300, timeout))


def _json_records(text: str) -> list[object]:
    stripped = text.strip()
    if not stripped:
        return []
    try:
        value = json.loads(stripped)
    except json.JSONDecodeError:
        records: list[object] = []
        for line in stripped.splitlines():
            try:
                records.append(json.loads(line))
            except json.JSONDecodeError as error:
                raise ValueError("Compose service state was malformed") from error
        return records
    return value if isinstance(value, list) else [value]


def compose_inventory(
    repository_root: str | os.PathLike[str],
    runner: Runner,
    *,
    project_name: str | None = None,
    timeout: float = 30,
) -> list[dict[str, str]]:
    """Return validated live Compose records including their project identity."""
    expected = _validated_project_name(project_name)
    result = runner.run(
        (*compose_command(repository_root, project_name=expected), "ps", "--all", "--format", "json"),
        check=False, timeout=timeout,
    )
    if result.returncode:
        raise RuntimeError("Compose service inventory is unavailable")
    inventory: list[dict[str, str]] = []
    for record in _json_records(result.stdout):
        if not isinstance(record, Mapping):
            raise ValueError("Compose service inventory was malformed")
        values = {
            "service": record.get("Service", record.get("service")),
            "state": record.get("State", record.get("state")),
            "health": record.get("Health", record.get("health", "")),
            "project": record.get("Project", record.get("project")),
        }
        if not all(isinstance(value, str) for value in values.values()):
            raise ValueError("Compose service inventory was malformed")
        service = values["service"]
        project = values["project"]
        state = values["state"].strip().casefold()
        health = values["health"].strip().casefold()
        if (
            service != service.strip() or project != project.strip()
            or not service.isascii() or not project.isascii()
            or _COMPOSE_SERVICE_NAME.fullmatch(service) is None
            or state not in _COMPOSE_STATES
            or health not in _COMPOSE_HEALTH
            or _COMPOSE_PROJECT_NAME.fullmatch(project) is None
        ):
            raise ValueError("Compose service inventory was malformed")
        inventory.append({"service": service, "state": state, "health": health, "project": project})
    if len({item["service"] for item in inventory}) != len(inventory):
        raise ValueError("Compose service inventory was malformed")
    return inventory


def compose_ps(
    repository_root: str | os.PathLike[str],
    runner: Runner,
    *,
    project_name: str | None = None,
    timeout: float = 30,
) -> dict[str, dict[str, str]]:
    """Read Compose v2 service state, accepting array and JSON-lines output."""

    result = runner.run(
        (*compose_command(repository_root, project_name=project_name), "ps", "--format", "json"),
        check=False,
        timeout=timeout,
    )
    if result.returncode:
        raise RuntimeError("Compose service state is unavailable")
    records = _json_records(result.stdout)
    states: dict[str, dict[str, str]] = {}
    for record in records:
        if not isinstance(record, Mapping):
            raise ValueError("Compose service state was malformed")
        service_value = record.get("Service", record.get("service"))
        state_value = record.get("State", record.get("state"))
        health_value = record.get("Health", record.get("health", ""))
        if not all(isinstance(value, str) for value in (service_value, state_value, health_value)):
            raise ValueError("Compose service state was malformed")
        raw_service = service_value.strip()
        if not raw_service.isascii():
            raise ValueError("Compose service state was malformed")
        service = raw_service.casefold()
        state = state_value.strip().casefold()
        health = health_value.strip().casefold()
        if not service or not state or (health_value and not health):
            raise ValueError("Compose service state was malformed")
        if _COMPOSE_SERVICE_NAME.fullmatch(service) is None:
            raise ValueError("Compose service state was malformed")
        if state not in _COMPOSE_STATES or health not in _COMPOSE_HEALTH or service in states:
            raise ValueError("Compose service state was malformed")
        states[service] = {"state": state, "health": health}
    return states
